@startuml
'https://plantuml.com/sequence-diagram

participant Transaction_A as tranA
database Database as DB
participant Transaction_B as tranB

autonumber
note right of DB
bill
<bill_id, issue_time, is_sync>
<A, 2, 0>
<B, 2, 0>
end note

tranA -> DB : START TRANSACTION
tranB -> DB : START TRANSACTION
tranA -> DB : SELECT COUNT(1) AS COUNTER FROM bill \n WHERE is_sync = 0 and issue_time <= 2
DB -> tranA
note left
<bill_id, issue_time, is_sync>
<A, 2, 0>
<B, 2, 0>
end note
tranA -> tranA : Extract A, B to another DB

tranB -> DB : INSERT INTO bill (bill_id, issue_time, is_sync) \n VALUES (C, 2, 0)
tranB -> DB : COMMIT
note right
<bill_id, issue_time, is_sync>
<A, 2, 0>
<B, 2, 0>
<C, 2, 0>
end note

tranA -> DB : UPDATE bill SET <b>is_sync = 1 \n WHERE is_sync = 0 and issue_time <= 2
note left
<bill_id, issue_time, is_sync>
<A, 2, 1>
<B, 2, 1>
<font color=red><b><C, 2, 1></b>
end note
tranA -> DB : COMMIT
tranA -> DB : SELECT COUNT(1) AS COUNTER FROM bill \n WHERE <b>is_sync = 1
DB -> tranA
note left
3
end note
@enduml
